services:
  db:
    container_name: db
    image: postgres:latest
    restart: no
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: assembleia
    ports:
      - "5432:5432"